name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Deploy only from main branch
  workflow_dispatch: # Manual trigger support

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Create .env from GitHub Secrets
      - name: Create .env file
        run: |
          echo "VITE_CALENDAR_API_KEY=${{ secrets.VITE_CALENDAR_API_KEY }}" >> .env
          echo "VITE_CALENDAR_ID=${{ secrets.VITE_CALENDAR_ID }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
          echo "VITE_API_SECRET_KEY=${{ secrets.VITE_API_SECRET_KEY }}" >> .env
          echo "VITE_TIME_LOG_CSV=${{ secrets.VITE_TIME_LOG_CSV }}" >> .env

      # 4️⃣ Install Dependencies
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Build for Production
      - name: Build project
        run: |
          npm run build
          echo "✅ Build completed!"

      # 6️⃣ Add .htaccess for Hostinger SPA & MIME Fix
      - name: Add Hostinger .htaccess
        run: |
          echo "Adding .htaccess..."
          cat <<EOT > dist/.htaccess
          # Force correct MIME types
          AddType application/javascript .js .jsx
          AddType application/json .webmanifest
          AddType text/css .css
          
          # SPA Routing - redirect all to index.html
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]

          # Cache busting for static assets
          <FilesMatch "\.(js|css|png|jpg|jpeg|svg|webp|ico)$">
            Header set Cache-Control "max-age=31536000, public"
          </FilesMatch>
          EOT

      # 7️⃣ Deploy to Hostinger via FTP
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOSTINGER_FTP_SERVER }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./dist
          server-dir: /public_html/
          log-level: minimal
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/src/*
