export const NAV_ITEMS = [
  {
    id: "rides",
    to: "/rides",
    label: "Claim Rides",
    icon: "DirectionsCar",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "clock",
    to: "/clock",
    label: "Time Clock",
    icon: "AccessTime",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "shootout",
    to: "/shootout",
    label: "Shootout Ride & Time Tracker",
    icon: "AirportShuttle",
    rolesVisible: ["admin", "driver", "shootout"],
  },
  {
    id: "info",
    to: "/info",
    label: "Drop-Off Info",
    icon: "Info",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "drop-guides",
    to: "/drop-guides",
    label: "Vehicle Tips",
    icon: "DirectionsCar",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "directory",
    to: "/directory",
    label: "Driver Directory",
    icon: "People",
    rolesVisible: ["admin", "driver", "shootout"],
  },
  {
    id: "calendar",
    to: "/calendar",
    label: "Calendar / Moovs",
    icon: "CalendarMonth",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "escalation",
    to: "/escalation",
    label: "Escalation Guide",
    icon: "Warning",
    rolesVisible: ["admin", "driver", "shootout"],
  },
  {
    id: "vehicle-calendar",
    to: "/vehicle-calendar",
    label: "Ride & Vehicle Calendar",
    icon: "Event",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "scan",
    to: "/scan",
    label: "Ticket Scanner",
    icon: "QrCodeScanner",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "tickets",
    to: "/tickets",
    label: "Tickets",
    icon: "ConfirmationNumber",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "admin-time-log",
    to: "/admin-time-log",
    label: "Admin Logs",
    icon: "TableChart",
    rolesVisible: ["admin"],
  },
  {
    id: "admin-user-manager",
    to: "/admin-user-manager",
    label: "User Manager",
    icon: "ManageAccounts",
    rolesVisible: ["admin"],
  },
  {
    id: "admin-notifications",
    to: "/admin/notifications",
    label: "Notifications",
    icon: "Notifications",
    rolesVisible: ["admin"],
  },
  {
    id: "ride-entry",
    to: "/ride-entry",
    label: "Add Ride",
    icon: "AddCircle",
    rolesVisible: ["admin"],
  },
];
