export const NAV_ITEMS = [
  {
    id: "rides",
    to: "/rides",
    label: "Claim Rides",
    icon: "DirectionsCar",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "clock",
    to: "/clock",
    label: "Time Clock",
    icon: "AccessTime",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "info",
    to: "/info",
    label: "Drop-Off Info",
    icon: "Info",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "drop-guides",
    to: "/drop-guides",
    label: "Vehicle Tips",
    icon: "DirectionsCar",
    rolesVisible: ["admin", "driver"],
    hidden: true,
  },
  {
    id: "directory",
    to: "/directory",
    label: "Directory & Escalations",
    icon: "ContactEmergency",
    rolesVisible: ["admin", "driver", "shootout"],
  },
  {
    id: "calendar",
    to: "/calendar",
    label: "Calendar & Availability",
    icon: "CalendarMonth",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "scan",
    to: "/scan",
    label: "Ticket Scanner",
    icon: "QrCodeScanner",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "tickets",
    to: "/tickets",
    label: "Tickets",
    icon: "ConfirmationNumber",
    rolesVisible: ["admin", "driver"],
  },
  {
    id: "admin-time-log",
    to: "/admin-time-log",
    label: "Admin Logs",
    icon: "TableChart",
    rolesVisible: ["admin"],
  },
  {
    id: "admin-user-manager",
    to: "/admin-user-manager",
    label: "User Manager",
    icon: "ManageAccounts",
    rolesVisible: ["admin"],
  },
  {
    id: "admin-notifications",
    to: "/admin/notifications",
    label: "Notifications",
    icon: "Notifications",
    rolesVisible: ["admin"],
  },
  {
    id: "ride-entry",
    to: "/ride-entry",
    label: "Add Ride",
    icon: "AddCircle",
    rolesVisible: ["admin"],
  },
];
